/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "base_wrapper.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PCToBase, PCToBase, 2)


PB_BIND(BaseToPC, BaseToPC, 2)



