/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_BASE_WRAPPER_PB_H_INCLUDED
#define PB_BASE_WRAPPER_PB_H_INCLUDED
#include <pb.h>
#include "base_command.pb.h"
#include "base_feedback.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PCToBase {
    pb_size_t commands_count;
    BaseCommand commands[16];
} PCToBase;

typedef struct _BaseToPC {
    pb_size_t feedbacks_count;
    BaseFeedback feedbacks[16];
} BaseToPC;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PCToBase_init_default                    {0, {BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default, BaseCommand_init_default}}
#define BaseToPC_init_default                    {0, {BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default, BaseFeedback_init_default}}
#define PCToBase_init_zero                       {0, {BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero, BaseCommand_init_zero}}
#define BaseToPC_init_zero                       {0, {BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero, BaseFeedback_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define PCToBase_commands_tag                    1
#define BaseToPC_feedbacks_tag                   1

/* Struct field encoding specification for nanopb */
#define PCToBase_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  commands,          1)
#define PCToBase_CALLBACK NULL
#define PCToBase_DEFAULT NULL
#define PCToBase_commands_MSGTYPE BaseCommand

#define BaseToPC_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  feedbacks,         1)
#define BaseToPC_CALLBACK NULL
#define BaseToPC_DEFAULT NULL
#define BaseToPC_feedbacks_MSGTYPE BaseFeedback

extern const pb_msgdesc_t PCToBase_msg;
extern const pb_msgdesc_t BaseToPC_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PCToBase_fields &PCToBase_msg
#define BaseToPC_fields &BaseToPC_msg

/* Maximum encoded size of messages (where known) */
#define BaseToPC_size                            560
#define PCToBase_size                            592

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
