/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_KICKER_PB_H_INCLUDED
#define PB_KICKER_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _Kicker {
    Kicker_NO_KICK = 0,
    Kicker_FLAT = 1,
    Kicker_CHIP = 2
} Kicker;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Kicker_MIN Kicker_NO_KICK
#define _Kicker_MAX Kicker_CHIP
#define _Kicker_ARRAYSIZE ((Kicker)(Kicker_CHIP+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
