/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_RADIO_WRAPPER_PB_H_INCLUDED
#define PB_RADIO_WRAPPER_PB_H_INCLUDED
#include <pb.h>
#include "radio_command.pb.h"
#include "radio_feedback.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _PCToBase {
    pb_callback_t command;
} PCToBase;

typedef struct _BaseToPC {
    pb_callback_t feedbacks;
} BaseToPC;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define PCToBase_init_default                    {{{NULL}, NULL}}
#define BaseToPC_init_default                    {{{NULL}, NULL}}
#define PCToBase_init_zero                       {{{NULL}, NULL}}
#define BaseToPC_init_zero                       {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define PCToBase_command_tag                     2
#define BaseToPC_feedbacks_tag                   1

/* Struct field encoding specification for nanopb */
#define PCToBase_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  command,           2)
#define PCToBase_CALLBACK pb_default_field_callback
#define PCToBase_DEFAULT NULL
#define PCToBase_command_MSGTYPE RadioCommand

#define BaseToPC_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  feedbacks,         1)
#define BaseToPC_CALLBACK pb_default_field_callback
#define BaseToPC_DEFAULT NULL
#define BaseToPC_feedbacks_MSGTYPE RadioFeedback

extern const pb_msgdesc_t PCToBase_msg;
extern const pb_msgdesc_t BaseToPC_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define PCToBase_fields &PCToBase_msg
#define BaseToPC_fields &BaseToPC_msg

/* Maximum encoded size of messages (where known) */
/* PCToBase_size depends on runtime parameters */
/* BaseToPC_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
